### ISSUE TITLE
is the API updated?

### ISSUE THREAD

**Issue by anisldn** [matomo-org/piwik-python-api#23]
hi @andrewschoen @nkuttler,

looking at the date of the last commit I noticed that the last date for 2 years for that I just wanted to know if the package is updated with the API(matomo) or not.

**Comment by nkuttler** [comment]
Not by me.

**Comment by mattab** [comment]
Hi @anisldn 

We are looking for help, please comment in https://github.com/matomo-org/piwik-python-api/issues/19 if you'd like to contribute. There is also an opened Pull request that needs testing & feedback, would be great if you can help test: https://github.com/matomo-org/piwik-python-api/pull/24
