### ISSUE TITLE
The API is a mess

### ISSUE THREAD

**Issue by nkuttler** [matomo-org/piwik-python-api#8]
To track a single request with the API requires far too much work and too many API calls. It needs a more elegant, pythonic interface.

**Comment by IZIREN** [comment]
Still no update? Should I even waste my time with this project?

**Comment by nkuttler** [comment]
I have moved on. This was for a client project that doesn't exist any more, and I stopped using Piwik personally.

**Comment by brendoncrawford** [comment]
I have been working on this in the `refactor` branch.  This is still a work in progress.

**Comment by mattab** [comment]
Please continue discussion in https://github.com/matomo-org/piwik-python-api/issues/19
